runtime: go114
env_variables:
  APP_MODE: production
inbound_services:
  - warmup
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
